name: run CEF_Scraper.py

on:
  schedule:
    - cron: '0 10 * * 1-5' # At 11:00 on every day-of-week from Monday through Friday

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repository Content
        uses: actions/checkout@v3 # checkout the repository content to github runner

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # install the python version needed
          
      - name: Install Python Packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Dig Into Repository Folders
        run: ls -la
        working-directory: ${{ github.workspace }}/Daily_Pricing
          
      - name: Execute Python Script # run CEF_Scraper.py
        run: python CEF_Scraper.py
          
      - name: Commit Files to Repository
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "update" --allow-empty)
          
      - name: Push Changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main 